image:
  file: .gitpod.Dockerfile
  context: apache

ports:
  # Web server
  - port: 8080
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore
tasks:
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
- name: Terminal
  command: >
    echo "";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";

